### ISSUE TITLE
kafka-socket 예제

### ISSUE THREAD

**Issue by clignkl** [sqisnms/snms-web#70]
브랜치 250211_socket
커밋 a73f24e791ea9269eb180f97eba45a31ce7becc4

docker-compose.yml
```
version: '3.8'
services:
  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT_LOCAL://:9092,PLAINTEXT_DOCKER://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT_LOCAL://localhost:9092,PLAINTEXT_DOCKER://kafka1:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_LOCAL:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_DOCKER
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - kafka_network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=Local-Kraft-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
    networks:
      - kafka_network

networks:
  kafka_network:

```

1. docker 에서 kafka 기동
2. websocket 및 consumer 기동
```
cd C:\Users\a\Documents\snms\git\snms-web
node --loader ts-node/esm server-websocket.ts
```
3. producer 기동
```
cd C:\Users\a\Documents\snms\git\snms-web
node --loader ts-node/esm server-producer.ts
```
4. http://localhost:3000/incident/list 에서 확인
